### ISSUE TITLE
logo.png and defaultusericon.png not loading in teams page

### ISSUE THREAD

**Issue by zach2898** [LeoKamgarCU/BetterIMWebsite#59]
![Image](https://user-images.githubusercontent.com/77704031/201509472-1cb090a5-37ef-4ff6-8e96-26da1b3c6d50.png)

**Comment by theo111111111** [comment]
I think this is because that page is in a whole different directory, so we may need to add './' to the image sources.? Or, try to implement the page so that it is not located in a subdirectory.
